FROM node:20-bookworm AS base
WORKDIR /app

COPY package*.json ./
COPY apps/web/package*.json ./apps/web/
COPY apps/worker/package*.json ./apps/worker/
RUN npm install

COPY . .
RUN npm run prisma:generate
RUN npm run build -w @convertitore/web

EXPOSE 3000
CMD ["npm", "run", "start", "-w", "@convertitore/web"]
